DROP DATABASE IF EXISTS smartphones;
DROP USER IF EXISTS `smart_user`@`%`;
CREATE DATABASE IF NOT EXISTS smartphones CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `smart_user`@`%` IDENTIFIED WITH mysql_native_password BY 'smart_pass';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `smartphones`.* TO `smart_user`@`%`;
FLUSH PRIVILEGES;